export const categoryResource = [
  // Fiction
  'Science Fiction',
  'Fantasy',
  'Mystery',
  'Romance',
  'Thriller',
  'Horror',
  'Literary Fiction',
  'Historical Fiction',
  'Young Adult',
  'Children\'s',
  'Graphic Novels & Comics',
  // Non-Fiction
  'Biography & Memoir',
  'Self-Help',
  'Business & Finance',
  'Health & Fitness',
  'History',
  'Science & Technology',
  'Philosophy',
  'Psychology',
  'Religion & Spirituality',
  'Travel',
  'Cooking & Food',
  'Art & Photography',
  'True Crime',
  'Politics & Current Events',
  'Education & Reference',
];